spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test-helper?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 4400
